### ISSUE TITLE
IOS8

### ISSUE THREAD

**Issue by siosheChina** [100apps/openshare#1]
好像有些方法是IOS8里面得。。IOS8以下的得改改。。。

**Comment by 100apps** [comment]
我在模拟下跑了一下，能启动。但是由于没有iOS7真机，所以不能掉起客户端分享。@siosheChina 能帮我看看具体是哪个API不能在iOS7下调用呢？可否把错误截个图呢？
![1](https://cloud.githubusercontent.com/assets/8075583/7810177/65b5060e-03d2-11e5-8565-cece8ca18313.jpg)

**Comment by siosheChina** [comment]
- (BOOL)containsString:(NSString *)aString NS_AVAILABLE(10_10, 8_0); 呵呵。别哭。。就是它

**Comment by 100apps** [comment]
非常感谢@siosheChina 
已修复:
https://github.com/100apps/openshare/commit/ba5016e7bc027386ba709d984bdd520811d966c6

**Comment by siosheChina** [comment]
用微博授权。好像有点问题，会出现“sso package or sign error” 的错误。。

**Comment by 100apps** [comment]
KEY的问题。默认的key没有经过审核，替换成自己的key进行测试。
