### ISSUE TITLE
好框架，分享，支付，做起来挺简单的，赞一个

### ISSUE THREAD

**Issue by songxing10000** [100apps/openshare#10]

**Comment by 100apps** [comment]
非常感谢！使用过程中如果有任何问题，可以随时和我邮件沟通，我会在第一时间解决。

**Comment by songxing10000** [comment]
从这个框架点到你博客，博客文章从最新的看到最后一，技术的确很厉害，最近一直做ios这块了吗







发自网易邮箱大师
在2015年07月15日 14:10，Guangfeng 写道:

非常感谢！使用过程中如果有任何问题，可以随时和我邮件沟通，我会在第一时间解决。

**Comment by 100apps** [comment]
是的，已入iOS坑。

另外，兄弟如果还有问题可以考虑直接发我的邮箱<gf@gfzj.us> 
在Github的issue交流有点奇怪:D

**Comment by songxing10000** [comment]
好的邮件联系





发自网易邮箱大师
在2015年07月15日 15:06，Guangfeng 写道:

是的，已入iOS坑。

另外，兄弟如果还有问题可以考虑直接发我的邮箱gf@gfzj.us
在Github的issue交流有点奇怪:D

**Comment by songxing10000** [comment]
发自网易邮箱大师
|
| 转发的邮件 |
|
发件人：songxing10000
发送日期：2015年07月20日 14:12
收件人：GF
主题：没有安装微博，如何提示用户
大神你好，今天遇到一个问题，假如用户没有安装微博，需要进行提示，不知道在哪里加入提示信息


发自网易邮箱大师
