### ISSUE TITLE
支付宝报错 -canOpenURL: failed for URL: "alipay://" - error: "This app is not allowed to query for scheme alipay"

### ISSUE THREAD

**Issue by hotdog45** [100apps/openshare#129]
支付宝报错-canOpenURL: failed for URL: "alipay://" - error: "This app is not allowed to query for scheme alipay"

link = "app_id=2017010304810638&biz_content=%7B%22out_trade_no%22%3A%222017042209411430%22%2C%22product_code%22%3A%22QUICK_MSECURITY_PAY%22%2C%22subject%22%3A%22%5Cb%E6%96%B0%E5%B9%B4%E7%AC%AC%E4%B8%80%E8%AF%BE%EF%BC%88%E6%94%B6%E8%B4%B9%EF%BC%89%22%2C%22total_amount%22%3A%229%22%7D&charset=UTF-8&format=JSON&method=alipay.trade.app.pay&notify_url=http%3A%2F%2Fapi.koudaitiku.net%2Fali%2Fapppay%2Fnotify.htm&sign=WzY13KUnUrA6b0u2WPc2KUidgQxwV21dVZj1H8ILoo2yh0Ghx5wMgVWxW5tAV%2BiStDhva1JSHkj2bGCj4BU6tbD5d5cuPTz%2B0ihxtaTYN9rVyWfuRvi%2BWiwbnut66zzOIODy1zeSk8FZduOHPu203kEYdJtb3zVpix54o5LgyoiZBh0wjqx%2F5jiLNk17ewEvt%2FmnphGyKKSxYAWSZ%2FaUg1fK8uBZlu%2BnYlnZvc4hwvr7sGMD1RZUQeLrbM2HnCaAALsc0am8HiisLnECilRxJLtE9mpWqb9iYA5TQeve0ECUnWmDYUeJQz10nBVSFbhY8clD%2Fpw0EbnWD61bTdliAQ%3D%3D&sign_type=RSA2&timestamp=2017-04-22+09%3A41%3A14&version=1.0"

**Comment by kasakui** [comment]
在你的Info.plist的文件中添加LSApplicationQueriesSchemes

**Comment by Liqiankun** [comment]
明显是权限问题，添加白名单！

**Comment by hotdog45** [comment]
已解决
