### ISSUE TITLE
假设没有安装对应客户端，这个能通过审核吗？

### ISSUE THREAD

**Issue by wang9262** [100apps/openshare#13]

**Comment by 100apps** [comment]
比如说，没有安装QQ。有两种解决方案：
1. 显示分享到QQ按钮。没有安装，走UIWebview h5。QQ分享的URL，Google一下都有。
```objc
if([OpenShare isQQInstalled]){
//OpenShare分享
}else{
//走h5
}
```
2. 不显示分享到QQ按钮：
```objc
if([OpenShare isQQInstalled]){
//显示分享按钮
}
```

默认情况下，如果没有安装QQ，会点击没反应，这个是不推荐的做法，有被拒的风险。而官方的SDK，提示安装QQ，则一般都会被拒绝。
