### ISSUE TITLE
升级 swift 4.2 后，取消分享也会跳到分享成功里

### ISSUE THREAD

**Issue by x1911** [100apps/openshare#164]
非常喜欢大大你的这个openshare，简单好用，可为什么不更新了？

**Comment by skybrim** [comment]
为鼓励用户自发分享喜爱的内容，减少“强制分享至不同群”等滥用分享能力，破坏用户体验的行为，微信公众平台分享功能将进行如下调整：

1、7月5日起新提交发布的版本，用户从小程序、小游戏中分享消息给好友时，开发者将无法获知用户是否分享完成，也无法在分享后立即获得群ID。该调整将在最新版开发者工具生效，可以等待基础库 2.0.8版本预先体验。

2、6月份新版微信客户端发布后，用户从微信内的网页或第三方App，分享消息给微信好友，以及分享到朋友圈，开发者将无法获知用户是否分享完成。

**Comment by x1911** [comment]
但关键是用旧的swift4.1还是可以正常的跳到分享失败中

**Comment by skybrim** [comment]
> 但关键是用旧的swift4.1还是可以正常的跳到分享失败中

分享成功or失败的回调，应该是通过微信客户端回调openURL中的参数来判断吧。
application:openURL:options:这个方法中，截取到回调openURL，无论分享成功还是失败都是不带参数的。但是微信支付的回调openURL，会携带参数。
这个应该和微信的客户端有关。
