### ISSUE TITLE
修正gif无法正常在微信显示问题 

### ISSUE THREAD

**Issue by dengbotian** [100apps/openshare#21]
需要把
            //gif
            dic[@"fileData"]= msg.file;
            dic[@"thumbData"]=msg.thumbnail ? [self dataWithImage:msg.thumbnail] : [self dataWithImage:msg.image scale:CGSizeMake(100, 100)];
            dic[@"objectType"]=@"8";

objectType 设置成 8,gif才会正常生效.

**Comment by 100apps** [comment]
非常感谢！
