### ISSUE TITLE
AliPay如果没有客户端的话，网页支付能实现么？

### ISSUE THREAD

**Issue by SuperY** [100apps/openshare#24]

**Comment by 100apps** [comment]
当然可以。

其实就是一个拼接url的过程。然后用webview load。

这个和没有安装qq客户端，要走h5分享到qq一样，已经在TODO里面了，近期会发布更新。 
------------------ Original ------------------

**Comment by weizhangCoder** [comment]
你支付宝成功了吗，我想问下你怎么弄的

**Comment by SuperY** [comment]
当时调试过，没有去实现。支付宝需要把Ali SDK里的自定义对象进行序列化，按照一定的格式组装下。可以参照https://github.com/nixzhu/MonkeyKing/blob/master/MonkeyKing/MonkeyKing.swift
