### ISSUE TITLE
分享给微信好友，在好友列表界面点击返回（取消分享）走Success分支

### ISSUE THREAD

**Issue by zhoujie903** [100apps/openshare#29]
分享给微信好友，在好友列表界面点击返回（相当于取消分享）走Success分支
没有一个值判断是成功还是取消分享
[OpenShare shareToWeixinSession:msg Success:^(OSMessage *message) {
        NSLog(@"微信分享到会话成功：\n%@",message);
        [KSToastView ks_showToast:@"分享成功"]; //没有一个值判断是成功还是取消分享
    } Fail:^(OSMessage *message, NSError *error) {
    }];

**Comment by 100apps** [comment]
取消分享会走Fail方法

**Comment by zhoujie903** [comment]
我是测试过的，无论是tag版本代码，还是Head版本代码都走了Success分支分支

**Comment by 100apps** [comment]
![img_0129](https://cloud.githubusercontent.com/assets/8075583/10725583/faff9b7c-7c07-11e5-8153-0b349ff17f53.PNG)

**Comment by zhoujie903** [comment]
@100apps 

是我的代码问题，SDK没问题

我现在应用程序的场景是：用原生微信SDK来支付；用你的SDK来分享（想排除UMeng分享）

原来的代码：
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
	[WXApi handleOpenURL:url delegate:self];
	if ([OpenShare handleOpenURL:url]) {        
        return YES;
    }
    return YES;
}

改为： 就OK了
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    if ([OpenShare handleOpenURL:url]) {
        [WXApi handleOpenURL:url delegate:self];
        return YES;
    }
}

**Comment by 100apps** [comment]
@zhoujie903 感谢使用

PS：
1. OpenShare支持微信、支付宝支付。并且服务器端pay.php也是无任何依赖实现的，我们自己的app也是实用OpenShare支付的，目前没有遇到任何问题。
2. github markdown支持 代码 格式，阅读效果会比较好一些。可以Google一下。

**Comment by rentaogithub** [comment]
可以知道分享取消的状态吗?
