### ISSUE TITLE
微信分享图片，名字30.dat

### ISSUE THREAD

**Issue by dulingkang** [100apps/openshare#30]
微信分享了图片，点击图片，导航栏上的名字是 如下 格式： 30.dat，我看这个content内容是从剪切板拷贝的，这个显示的名字可以自己定义一下吗

**Comment by mrkey0310** [comment]
在+(NSString*)genWeixinShareUrl:(OSMessage*)msg to:(int)shareTo 方法里面，分享图片设置msg 的title. title就是显示的名字

**Comment by dulingkang** [comment]
![1323524e4c6531cb9d9b0c0e3902c45a](https://cloud.githubusercontent.com/assets/11434105/10928815/1f391780-82e7-11e5-975e-53a803f5be51.png)
看导航栏上的字22.dat， 在+(NSString)genWeixinShareUrl:(OSMessage)msg to:(int)shareTo 方法里，加了断点，msg.title是有值的
```
 Printing description of msg->_title:
Hello msg.title
```

**Comment by mrkey0310** [comment]
你认真的看一下源码，在图片的大括号里面，title是没有加进去字典里面的.....

**Comment by dulingkang** [comment]
对，在有图片时，没把title加入到字典，加上就可以了，多谢了！
