### ISSUE TITLE
可以支持swift不

### ISSUE THREAD

**Issue by icecooly** [100apps/openshare#32]
见标题

**Comment by 100apps** [comment]
目前为止，我自己还没有对swift做过任何测试。

github上有一个swift实现的openshare：<https://github.com/firewolf-ljw/rawshare>
另外，如果想在swift项目中使用OC版的openshare，可以参考[OC和swift混编](http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift)
