### ISSUE TITLE
分享到QQ空间偶发性失败

### ISSUE THREAD

**Issue by iOSNerd** [100apps/openshare#34]
使用OpenShare分享到QQ空间时，有时候会失败，“重新发送”几次后才成功。而在同一网络下，使用其他的接入了QQ原生SDK的APP分享到QQ空间，总会成功。
下面是一些现场，希望能有帮助
1、分享到QQ空间
![image](https://cloud.githubusercontent.com/assets/4392747/10934256/bdad0b42-8319-11e5-8062-3687e817190c.png)
2、分享失败
![image](https://cloud.githubusercontent.com/assets/4392747/10934181/3b3cbb12-8319-11e5-8a33-2b8f4b74cbe7.png)
3、分享失败时的包
![image](https://cloud.githubusercontent.com/assets/4392747/10934201/57995d42-8319-11e5-81b7-74e39f9287f1.png)
4、点了几次“重新发送”后，发送成功了，add_share_pic:
![image](https://cloud.githubusercontent.com/assets/4392747/10934240/a438cee4-8319-11e5-956a-97ae68c0f7d9.png)

**Comment by Duzj** [comment]
对，我也遇到这个问题，我用demo中的url 每次都成功，换成自己的url 放在demo中也会出现这种情况，我感觉是不是最后拼接的地址有什么问题？

**Comment by 100apps** [comment]
贴一下代码吧 
------------------ Original ------------------

**Comment by Duzj** [comment]
我直接用demo中的代码，只是最后一句换了个url，麻烦看下，特别是 qq空间
-(void)qqViewHandler:(UIButton*)btn{
    UISegmentedControl *seg=(UISegmentedControl*)[panel viewWithTag:2002];
    OSMessage *msg=[[OSMessage alloc] init];
    msg.title=@"Hello OpenShare (msg.title)";
    if (btn.tag>=2) {
        msg.image=testImage;
        msg.thumbnail=testThumbImage;
        msg.desc=@"这里写的是msg.description";
    }
    if(btn.tag==3){
        msg.link=@"http://sports.qq.com/a/20120510/000650.htm";
    }else if(btn.tag==4){
        msg.link=@"http://wfmusic.3g.qq.com/s?g_f=0&fr=&aid=mu_detail&id=2511915";
        msg.multimediaType=OSMultimediaTypeAudio;
    }else if(btn.tag==5){
        msg.link=@"http://v.youku.com/v_show/id_XOTU2MzA0NzY4.html";
        msg.multimediaType=OSMultimediaTypeVideo;
    }
    
    msg.link = @"http://app.systoon.com/?uuid=16ceb0b3-4bc8-43f8-a637-f89fd4a31865&fw=null";

**Comment by iOSNerd** [comment]
分享失败时的OSMessage对象（保密需要，涂黑了URL，请谅解）
![image](https://github-cloud.s3.amazonaws.com/assets%2F4392747%2F10957940%2F1c6e477e-83a4-11e5-8d49-cd01a948e2ed.png)
PS：在使用原生SDK分享到QQ空间时，抓包并没有发现share/add_share_pic接口的调用

**Comment by 100apps** [comment]
@iOSNerd @Duzj 
/10989616/93fc2c12-8484-11e5-96fb-00440d8f983f.png)

QQ空间分享失败，我认为应该是是QQ空间自己的反垃圾算法导致的，和分享没关系。

我用官方SDK<http://wiki.open.qq.com/wiki/mobile/SDK%E4%B8%8B%E8%BD%BD>做了测试，同样会有分享失败的情况。

分享的url、标题、描述都有可能导致分享失败。
