### ISSUE TITLE
刚下载了demo运行，发现“分享文本消息”到QQ空间报错

### ISSUE THREAD

**Issue by songxing10000** [100apps/openshare#40]
在QQ空间分享失败后，会有个返回，重试的alterview，点重试也失败
有时候，点返回会返回多次，望修复

![d737eafdb953be23b1844741f5a57431](https://cloud.githubusercontent.com/assets/10040131/11303034/a6f3fa54-8fdb-11e5-95a5-6037bb21ff92.png)

**Comment by songxing10000** [comment]
顺便再问下大神，去腾讯平台创建应用后，有了appid appkey不提交审核，到时候分享的来源会是自己申请的名字还是未经审核的应用啊，新浪没通过就显示未审核，不知道QQ微信也是这样显示吗

**Comment by 100apps** [comment]
http://wiki.open.qq.com/wiki/mobile/SDK%E4%B8%8B%E8%BD%BD

>1. 关闭以下功能
第三方APP直接上传图片和视频到空间，分享的图片支持在动态直接展示，视频支持动态里直接播放
说明：开发接口文档 《IOS SDK API V2.9.5使用说明.doc》 附在完整版doc目录

QQ空间的分享现在只保留了news类型，其他的都关闭了。
