### ISSUE TITLE
Bug Report: 微信 6.3.7 修改了分享后的行为

### ISSUE THREAD

**Issue by Vayn** [100apps/openshare#41]
@100apps 昨天微信自动升级到 6.3.7，__升级后从应用分享链接到微信不再自动跳回原应用。__

不知道是微信修改了分享逻辑，还是连协议一块改了。导致 `OpenShare shareToWeixinTimeline:msg` 的回调无法被调用。

__UPDATE:__ 确认是微信改协议了……

**Comment by 100apps** [comment]
确定demo无法用吗？

**Comment by Vayn** [comment]
我是在自己应用上突然发现用不成了，demo 还没试验。
现在人在外面，手上没电脑。

**Comment by 100apps** [comment]
我这里测试demo是OK的，所以麻烦再确定一下，看看问题出在哪里。

**Comment by Vayn** [comment]
找到原因了，是因为我修改了`OpenShare connectWeixinWithAppId:` 的 APP ID，但是没改 `info.plist` 里的相应键值，与 OpenShare 无关。感谢回复 :smile:
