### ISSUE TITLE
微信分享后不能返回APP

### ISSUE THREAD

**Issue by opencheer** [100apps/openshare#42]
不知道是哪里没有设置

**Comment by opencheer** [comment]
[OpenShare shareToWeixinSession:msg Success:^(OSMessage *message) {
                NSLog(@"微信分享到会话成功：\n%@",message);
            } Fail:^(OSMessage *message, NSError *error) {
                NSLog(@"微信分享到会话失败：\n%@\n%@",error,message);
            }];
这个地方的回调也没有执行

**Comment by 100apps** [comment]
demo是否能正常运行？

**Comment by opencheer** [comment]
解决了，是我的URL Scheme没有设置对
