### ISSUE TITLE
ios8.4(12H143) 微信登录不能

### ISSUE THREAD

**Issue by superlbr** [100apps/openshare#43]
会调用微信，但貌似回调没有出现

**Comment by 100apps** [comment]
demo是否也有同样的问题？

**Comment by superlbr** [comment]
demo在ios9.1下OK，办公室里2台都可以

**Comment by 100apps** [comment]
可以参考一下[文档](https://github.com/100apps/openshare#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)，看看是否漏掉了其中某一步？

**Comment by superlbr** [comment]
反复测试，确实有问题，

**Comment by superlbr** [comment]
func application(app: UIApplication, openURL url: NSURL, options: [String : AnyObject]) -> Bool {

**Comment by superlbr** [comment]
没有响应，但是ios9可以

**Comment by superlbr** [comment]
ios 新手，debug不出来

**Comment by 100apps** [comment]
你的意思是，clone了demo，在iOS9上运行没有问题。但是到了iOS8.4上面，微信登录不能回调，对吗？

**Comment by superlbr** [comment]
嗯

**Comment by superlbr** [comment]
我找到问题，让我确认下

**Comment by superlbr** [comment]
AppDelegate下面有两个方法含有openurl。
一个是func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {}
另一个是  func application(app: UIApplication, openURL url: NSURL, options: [String : AnyObject]) -> Bool {  }
我是用了后者，改为前者就ok了

**Comment by 100apps** [comment]
👍

**Comment by superlbr** [comment]
参考这个，
http://stackoverflow.com/questions/33428963/unable-to-call-appdelegate-openurl-while-using-the-dropbox-sdk。
IOS9启用了新的function，后者，前者要被废弃了。。。
