### ISSUE TITLE
微博不能同时分享图片和链接

### ISSUE THREAD

**Issue by wangjinwei0806** [100apps/openshare#50]

**Comment by wangjinwei0806** [comment]
![1be83562-1656-49d0-ab1d-bc2bb8de58eb](https://cloud.githubusercontent.com/assets/3974508/12545873/cf4aafb0-c380-11e5-9d7d-631a5dc74246.png)
z这段代码没实现吗

**Comment by laughmaker** [comment]
在写message对象的时候，把链接放到title里，同时把link置为nil，就可以了。
最好自己封装一下吧

**Comment by wangjinwei0806** [comment]
thank you ...
