### ISSUE TITLE
微信分享图片失败！

### ISSUE THREAD

**Issue by shengwanlin** [100apps/openshare#58]

**Comment by zzgo** [comment]
同样，提示应用消息数据错误

**Comment by zzgo** [comment]
我是用的cocoapods上的0.0.1版。
图片也用UIImageJPEGRepresentation和UIImagePNGRepresentation转化为NSData类型。
但是都失败了。

**Comment by zzgo** [comment]
解决了，微信限制了分享图片的大小。
