### ISSUE TITLE
集成出现了一些bug不知道是 什么原因

### ISSUE THREAD

**Issue by weizhangCoder** [100apps/openshare#60]
1.微博分享的时候，要是有链接类型就会奔溃OpenShare+Weibo.m 的56行
2.QQ分享进去qq列表点击之后不会分享
3.分享微信app message error 错误

**Comment by CoderLISIDI** [comment]
我的QQ分享好的, 微信 是应用消息错误, 微博更是直接回退....

**Comment by weizhangCoder** [comment]
是啊，微信咋们的情况是一样的，感觉问题还比较多，不知道有谁继承好的，能说说这是什么问题。

**Comment by CoderLISIDI** [comment]
我的解决了, 我的原因是分享的图片大小超出了限制

**Comment by weizhangCoder** [comment]
好，谢谢，确实是这样的，但是我写的连接也会分享失败，要是单独分享文字也会失败，只有分享一个文字和一个简单的图片，就可以成功。
