### ISSUE TITLE
请教一些基础问题

### ISSUE THREAD

**Issue by xiongzenghuigithub** [100apps/openshare#8]
1. 里面的一些url参数拼接，大牛是怎么知道的？ 以后他万一变了？
2. 里面的一些url schema 在哪里找到的？

求大牛解释下，谢谢！！！

**Comment by 100apps** [comment]
@xiongzenghuigithub 你可以看看这里：http://www.gfzj.us/series/openshare/2015/05/21/openshare-how.html
