### ISSUE TITLE
如何调用支付宝网页支付

### ISSUE THREAD

**Issue by Leo2016** [100apps/openshare#91]
各位大神，由于特殊原因，项目里目前只集成了openshare，没有支付宝的sdk，有没有什么办法可以在没有安装支付宝的时候调用支付宝网页支付？

**Comment by 100apps** [comment]
支付宝网页支付有[两种形式](https://b.alipay.com/signing/productSet.htm?navKey=all)：
1. SDK发起的（没有安装支付宝app，但是集成了支付宝SDK），这种叫做“移动支付”。虽然是h5页面，但是和app本身是一样的。
2. 手机网站发起的，这种支付和PC浏览器支付类似，这种叫做“手机网站支付”。

虽然都是手机网页中支付，但是这是两个完全不同的产品，签约的时候需要注意，需要分别单独和支付宝签约的。

第1种方式中，支付宝SDK调用webview实际上是声称了一个加密的url，然后打开。关键是我目前不知道他们的加密算法，所以无法生成这样一个加密过的url。这种情况下，目前openshare无法解决（其实尝试过，但是没成功，或许以后可以支持）。所以我们自己的app也只好继承了支付宝sdk。
第2种方法就简单了，直接嵌套一个webview就和移动端网站一样就可以了。和openshare无关，走webview即可。但是要确保签约了“手机网站支付”。

另外，我很好奇，到底是什么原因？

**Comment by Leo2016** [comment]
感谢大神，想搞的就是第二种那种，但是一直没搜到相关的资料，🙏大神提点
